default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: Autoflake
        args:
          - --expand-star-imports
          - --ignore-init-module-imports
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      name: Black
      language_version: python3.9
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-merge-conflict
        # exclude files where underlines are not distinguishable from merge conflicts
        exclude: ^(README(\.rst|\.md)|docs/.*\.rst)$
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
        exclude: ^(.drone.yml|.pre\-commit\-config\.yaml)$
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: requirements-txt-fixer
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Import Sort
        args:
          - --settings=.
        exclude: /__init__\.py$
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      name: Flake8
      additional_dependencies: ["flake8-bugbear==20.1.4"]
