[tool.poetry]
name = "as-beamline-library"
version = "0.1.0"
description = "The template and example beamline library to be forked per beamline."
authors = ["Stephen Mudie <stephenm@ansto.gov.au>"]

[tool.poetry.dependencies]
python = "^3.9"
as-acquisition-library = {git = "ssh://git@bitbucket.synchrotron.org.au:7999/~mudies/as-acquisition-library.git", rev = "master"}

[tool.poetry.dev-dependencies]
black = "^22.1.0"
pre-commit = "^2.17.0"
pytest = "^7.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
