[tool.poetry]
name = "mx3-beamline-library"
version = "0.1.8"
description = "Ophyd devices and bluesky plans."
authors = ["Stephen Mudie <stephenm@ansto.gov.au>"]

[[tool.poetry.source]]
name = "cachedpypi"
url = "https://pypi.asci.synchrotron.org.au/root/pypi/+simple"
secondary = true

[[tool.poetry.source]]
name = "asci-dev"
url = "https://pypi.asci.synchrotron.org.au/asci/dev/+simple"
secondary = true

[[tool.poetry.source]]
name = "asci-prod"
url = "https://pypi.asci.synchrotron.org.au/asci/prod/+simple"
secondary = true

[[tool.poetry.source]]
name = "mx3dev"
url = "https://pypi.asci.synchrotron.org.au/mx3/dev/+simple"
secondary = true

[tool.poetry.dependencies]
python = "^3.9"
ophyd = "1.6.4"
bluesky = "1.8.3"
as-acquisition-library = "0.4.1"
as-redis-signal = {git = "https://bitbucket.synchrotron.org.au/scm/ec/as-redis-signal.git", rev = "main"}
requests = "2.27.1"

[tool.poetry.dev-dependencies]
black = "22.3.0"
pre-commit = "2.18.1"
pytest = "7.1.1"
Sphinx = "4.5.0"
sphinx-rtd-theme = "0.5.2"
alabaster = "0.7.12"
pylint = "2.13.4"
flake8 = "4.0.1"
isort = "5.10.1"
pytest-html = "3.1.1"
pytest-cov = "3.0.0"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
